version: '3.7'
services:
 redis:
  image: "redis:alpine"
  ports:
   - "6379:6379"
  expose:
   - 6379
  restart:
   always
  
 app:
  image: node:latest
  volumes:
   - ./server:/usr/src/app
  working_dir: /usr/src/app
  command: bash -c "npm install && npm run start"
  ports:
    - 3000:3000
  expose:
    - 3000